var constants ={
    ABSENCE_TYPES_LOAD_SUCCEEDED: 'ABSENCE_TYPES_LOAD_SUCCEEDED',
    ABSENCE_TYPE_CHANGED: 'ABSENCE_TYPE_CHANGED',

    ABSENCE_LOAD_SUCCEEDED: 'ABSENCE_LOAD_SUCCEEDED',
    ABSENCE_CREATE_SUCCEEDED: 'ABSENCE_CREATE_SUCCEEDED',
    ABSENCE_DELETE_SUCCEEDED: 'ABSENCE_DELETE_SUCCEEDED',

    ABSENCE_TYPE_COLORS: {
        '1': 'red',
        '2': 'green'
    }
};

module.exports = constants;
