var constants = {
    GOOGLE_SIGN_IN_SUCCEEDED: 'GOOGLE_SIGN_IN_SUCCEEDED',
    GET_LOGGED_IN_EMPLOYEE_SUCCEEDED: 'GET_LOGGED_IN_EMPLOYEE_SUCCEEDED',

    EMPLOYEE_LOAD_SUCCEEDED: 'EMPLOYEE_LOAD_SUCCEEDED',

    ABSENCE_TYPES_LOAD_SUCCEEDED: 'ABSENCE_TYPES_LOAD_SUCCEEDED',
    ABSENCE_TYPE_CHANGED: 'ABSENCE_TYPE_CHANGED',

    ABSENCE_LOAD_SUCCEEDED: 'ABSENCE_LOAD_SUCCEEDED',
    ABSENCE_CREATE_SUCCEEDED: 'ABSENCE_CREATE_SUCCEEDED',
    ABSENCE_UPDATE_SUCCEEDED: 'ABSENCE_UPDATE_SUCCEEDED',
    ABSENCE_DELETE_SUCCEEDED: 'ABSENCE_DELETE_SUCCEEDED',

    SCROLLED_TO_TOP: 'SCROLLED_TO_TOP',
    SCROLLED_TO_BOTTOM: 'SCROLLED_TO_BOTTOM',

    MONTH_NAMES: ['Januar', 'Februar', 'Mars', 'April', 'Mai', 'Juni', 'Juli',
    'August', 'September', 'Oktober', 'November', 'Desember'],

    ABSENCE_TYPE_COLORS: {
        'billable': '#59cbe8',
        'nonbillable': '#fdd757',
        'unavailable': '#f8485e',
        'weekend': '#eeeeee'
    }
};

module.exports = constants;
